### ISSUE TITLE
It shows always the same icon

### ISSUE THREAD

**Issue by semente** [zeten30/chatstatus#5]
It shows always the same icon as in the screenshot below:

![screenshot from 2015-05-12 11 35 12](https://cloud.githubusercontent.com/assets/29862/7589754/01532d86-f89b-11e4-99fa-433380edc691.png)

Changing status through the drop down menu works.

I'm on Debian Jessie (GNOME 3.14).

Thanks!

**Comment by zeten30** [comment]
Hi,

this icon is used if "custom status" is used. Status not in: available, dnd, away, offline, hidden.

Check your status with commands
 * mc-tool list (it shows account/s ID) 
 * mc-tool show <ID> and search for string Current: <some string>

I'm free to add detection of new statuses like 'online' can be same as 'available'... etc.

**Comment by semente** [comment]
Hi, I'm not using any custom status... The string in Current line is:

    Current: available (2) ""

**Comment by zeten30** [comment]
Hi, you have only one account ore more?

**Comment by semente** [comment]
2 xmpp, 2 IRC...

**Comment by semente** [comment]
Removed the IRC accounts and now it works

**Comment by zeten30** [comment]
I'm also using IRC + xmmp. I was solving this issue few months ago. This function should ignore IRC and disabled accounts. Current: "" in IRC account is used for IRC nickname.

function _is_managable_account(accid) {
    var is_managable = true;

    //Enabled account?
    var AccState = new String(GLib.spawn_command_line_sync('mc-tool show ' + accid.replace(/,/g,""))[1]);
    var AccEnabled = new String(AccState.match(/Enabled:.*/));
    AccEnabled = AccEnabled.replace(/Enabled: /,"");
    AccEnabled = AccEnabled.trim();

    if(! accid.match(/irc\//) == null) { 
        is_managable = false;
    }

    if(AccEnabled.match(/enabled/) == null) { 
        is_managable = false;
    }

    return is_managable;
}

Can you put your IRC accounts back for a while and send me output of "mc-tool list". I'm curious why IRC accounts were not ignored.

**Comment by semente** [comment]
There you go:

```
$ mc-tool list
gabble/jabber/foo0
gabble/jabber/bar0
idle/irc/test0
salut/local_xmpp/account0
```

Note that here I got ```Current:  (0) ""```:

```
$ mc-tool show idle/irc/test0
     Account: idle/irc/test0
Display Name: test on Debian Servers
  Normalized: test
     Enabled: enabled
        Icon: im-irc
    Connects: only when requested
    Nickname: test
     Service: debian-servers

Presences:
   Automatic: available (2) ""
     Current:  (0) ""
   Requested: available (2) ""
    Changing: yes

        (bool) use-ssl = false
      (string) server = irc.debian.org
      (string) charset = UTF-8
        (uint) port = 6667
      (string) account = test
```

**Comment by zeten30** [comment]
Hi, I've fixed regexp matching - last git version should work OK. You can give me a review on https://extensions.gnome.org/ to get latest version there. 

![screenshot from 2015-05-18 10 36 02](https://cloud.githubusercontent.com/assets/1825873/7677191/627432a0-fd4a-11e4-959e-f5529f5de38b.png)
