### ISSUE TITLE
mark as away when session is locked

### ISSUE THREAD

**Issue by oupala** [zeten30/chatstatus#6]
Could it be possible to add the feature to mark as away when session is locked?

**Comment by zeten30** [comment]
Nice idea. However, I'm not going to implement this. Empathy is not actively maintained and gnome online accounts dropped telepathy support recently (http://pkgs.fedoraproject.org/cgit/rpms/gnome-online-accounts.git/commit/?h=f24&id=a4f03c0fc2a23f8a036c759498b0a64d71825ffc).

I will not continue with this extension development & switch to Pidgin

**Comment by oupala** [comment]
Ok, I understand your point of view if empathy is not maintained any more.

Do you know what will be the next official client of Gnome Shell? I'm using debian and I wonder if empathy will also be removed from debian Gnome Shell...

**Comment by zeten30** [comment]
In tentative / design state https://wiki.gnome.org/Design/Apps/Chat .. no other ideas

**Comment by oupala** [comment]
Many thanks for these informations.

**Comment by zeten30** [comment]
My current setup is:

Packages:
pidgin-hangouts-0-35.20160803hgc5f97d3.fc24.noarch
pidgin-window-merge-0.3-6.fc24.x86_64
pidgin-2.11.0-1.fc24.x86_64
purple-plugin_pack-pidgin-2.7.0-3.fc24.x86_64

Gnome shell extensions
https://extensions.gnome.org/extension/782/pidgin-im-integration/
https://extensions.gnome.org/extension/1031/topicons/
